version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: "Test"
          command: make test
      - run:
          name: "Build"
          command: make build
